[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
py_version = "37"
line_length = 100
atomic = true
combine_as_imports = true
force_sort_within_sections = true
profile = "black"

[tool.pylint.basic]
# Required to make packages with Cython extensions work
extension-pkg-whitelist = "pydantic"
# Allows shorter names than the default regex,
# which is in pylint.checkers.base.SnakeCaseStyle.DEFAULT_NAME_RGX
argument-rgx = "(([a-z][a-z0-9_]*)|(_[a-z0-9_]*)|([A-Z]))$"
variable-rgx = "(([a-z][a-z0-9_]*)|(_[a-z0-9_]*)|([A-Z]))$"
function-rgx = "(([a-z][a-z0-9_]*)|(_[a-z0-9_]*)|([A-Z]))$"

[tool.pylint.format]
# Let Black handle line length
max-line-length = 300

[tool.pylint.messages_control]
# Most of these are disabled to prevent issues with dependencies being difficult to inspect
# pylint FAQ recommends disabling:
# wrong-import-order when using isort
# missing-module-docstring,missing-class-docstring,missing-function-docstring when using pydocstyle
disable = """
R,fixme,no-member,unsupported-membership-test,unsubscriptable-object
unsupported-assignment-operation,not-an-iterable,too-many-lines,wrong-import-order,bad-continuation,
wrong-import-position,missing-module-docstring,missing-class-docstring,missing-function-docstring,logging-fstring-interpolation
"""

[tool.pylint.reports]
score = false